title: Get to know Mridul
email: mridulk@iisc.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  Write a short description of your site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mridul-qm.github.io/mridul.github.io/" # the base hostname & protocol for your site

theme: jekyll-theme-architect

plugins: 
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge
